databases:
  - name: newdb
    plan: free
    databaseName: new
    user: new

services:
  - type: web
    plan: free
    name: new
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn new.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
